export const recentProjects = [
    { name: "پروژه برج سیورا", progress: 75, status: "در حال اجرا" },
    { name: "مجتمع مسکونی آریا", progress: 45, status: "طراحی" },
    { name: "پروژه تجاری پارس", progress: 90, status: "تکمیل" },
    { name: "پروژه ویلاهای شمال", progress: 60, status: "در حال اجرا" },
    { name: "مرکز خرید ستاره", progress: 30, status: "طراحی" },
    { name: "برج اداری پرشیا", progress: 95, status: "تکمیل" },
    { name: "مجتمع ورزشی المپیک", progress: 50, status: "در حال اجرا" },
    { name: "پارک علم و فناوری", progress: 25, status: "طراحی" },
    { name: "هتل بین‌المللی دریا", progress: 100, status: "تکمیل" },
    { name: "پل شهید احمدی", progress: 80, status: "در حال اجرا" },
    { name: "مجتمع تجاری کوروش", progress: 40, status: "طراحی" },
    { name: "استادیوم ملی", progress: 70, status: "در حال اجرا" },
    { name: "برج مسکونی نگین", progress: 85, status: "در حال اجرا" },
    { name: "پروژه باغ شهر", progress: 20, status: "طراحی" },
    { name: "مرکز پزشکی تخصصی", progress: 100, status: "تکمیل" },
    { name: "پروژه راه‌آهن سریع", progress: 65, status: "در حال اجرا" },
    { name: "مجتمع توریستی چمران", progress: 55, status: "در حال اجرا" },
    { name: "برج تجاری سپهر", progress: 35, status: "طراحی" },
    { name: "پروژه متروی شهر", progress: 75, status: "در حال اجرا" },
    { name: "دانشگاه بین‌المللی", progress: 90, status: "تکمیل" },
    { name: "مجتمع صنعتی کاوه", progress: 50, status: "در حال اجرا" },
    { name: "پروژه سینمایی شهر", progress: 15, status: "طراحی" },
    { name: "برج مسکونی آرمان", progress: 100, status: "تکمیل" },
    { name: "پارکینگ طبقاتی مرکز", progress: 70, status: "در حال اجرا" },
    { name: "مرکز تحقیقاتی نوآوری", progress: 40, status: "طراحی" },
    { name: "پروژه سد امیرکبیر", progress: 85, status: "در حال اجرا" },
    { name: "مجتمع تجاری ارگ", progress: 95, status: "تکمیل" },
    { name: "برج اداری پیشرو", progress: 60, status: "در حال اجرا" },
    { name: "پروژه فرودگاه جدید", progress: 30, status: "طراحی" },
    { name: "شهرک سلامت", progress: 100, status: "تکمیل" }
];