export const recentProjects = [
    { id: 1, name: "پروژه برج سیورا", progress: 75, status: "در حال اجرا" },
    { id: 2, name: "مجتمع مسکونی آریا", progress: 45, status: "طراحی" },
    { id: 3, name: "پروژه تجاری پارس", progress: 90, status: "تکمیل" },
    { id: 4, name: "پروژه ویلاهای شمال", progress: 60, status: "در حال اجرا" },
    { id: 5, name: "مرکز خرید ستاره", progress: 30, status: "طراحی" },
    { id: 6, name: "برج اداری پرشیا", progress: 95, status: "تکمیل" },
    { id: 7, name: "مجتمع ورزشی المپیک", progress: 50, status: "در حال اجرا" },
    { id: 8, name: "پارک علم و فناوری", progress: 25, status: "طراحی" },
    { id: 9, name: "هتل بین‌المللی دریا", progress: 100, status: "تکمیل" },
    { id: 10, name: "پل شهید احمدی", progress: 80, status: "در حال اجرا" },
    { id: 11, name: "مجتمع تجاری کوروش", progress: 40, status: "طراحی" },
    { id: 12, name: "استادیوم ملی", progress: 70, status: "در حال اجرا" },
    { id: 13, name: "برج مسکونی نگین", progress: 85, status: "در حال اجرا" },
    { id: 14, name: "پروژه باغ شهر", progress: 20, status: "طراحی" },
    { id: 15, name: "مرکز پزشکی تخصصی", progress: 100, status: "تکمیل" },
    { id: 16, name: "پروژه راه‌آهن سریع", progress: 65, status: "در حال اجرا" },
    { id: 17, name: "مجتمع توریستی چمران", progress: 55, status: "در حال اجرا" },
    { id: 18, name: "برج تجاری سپهر", progress: 35, status: "طراحی" },
    { id: 19, name: "پروژه متروی شهر", progress: 75, status: "در حال اجرا" },
    { id: 20, name: "دانشگاه بین‌المللی", progress: 90, status: "تکمیل" },
    { id: 21, name: "مجتمع صنعتی کاوه", progress: 50, status: "در حال اجرا" },
    { id: 22, name: "پروژه سینمایی شهر", progress: 15, status: "طراحی" },
    { id: 23, name: "برج مسکونی آرمان", progress: 100, status: "تکمیل" },
    { id: 24, name: "پارکینگ طبقاتی مرکز", progress: 70, status: "در حال اجرا" },
    { id: 25, name: "مرکز تحقیقاتی نوآوری", progress: 40, status: "طراحی" },
    { id: 26, name: "پروژه سد امیرکبیر", progress: 85, status: "در حال اجرا" },
    { id: 27, name: "مجتمع تجاری ارگ", progress: 95, status: "تکمیل" },
    { id: 28, name: "برج اداری پیشرو", progress: 60, status: "در حال اجرا" },
    { id: 29, name: "پروژه فرودگاه جدید", progress: 30, status: "طراحی" },
    { id: 30, name: "شهرک سلامت", progress: 100, status: "تکمیل" }
];