export const inventoryData = [
    { item: "سیمان", stock: "450 تن", status: "موجود" },
    { item: "میلگرد", stock: "120 تن", status: "کم موجود" },
    { item: "آجر", stock: "8500 عدد", status: "موجود" },
    { item: "شن و ماسه", stock: "25 متر مکعب", status: "سفارش داده شده" },
    { item: "آهن", stock: "320 تن", status: "موجود" },
    { item: "گچ", stock: "600 تن", status: "کم موجود" },
    { item: "سنگ نما", stock: "1200 عدد", status: "سفارش داده شده" },
    { item: "شیشه", stock: "150 متر مربع", status: "موجود" },
    { item: "سرامیک", stock: "700 عدد", status: "کم موجود" },
    { item: "لوله", stock: "400 متر", status: "موجود" },
    { item: "سیم برق", stock: "2000 متر", status: "موجود" },
    { item: "رنگ", stock: "500 کیلوگرم", status: "کم موجود" },
    { item: "چوب", stock: "100 قطعه", status: "سفارش داده شده" },
    { item: "پنجره", stock: "50 عدد", status: "موجود" },
    { item: "در", stock: "30 عدد", status: "کم موجود" },
    { item: "کابل شبکه", stock: "800 متر", status: "موجود" },
    { item: "لامپ", stock: "120 عدد", status: "سفارش داده شده" },
    { item: "کلید و پریز", stock: "400 عدد", status: "موجود" },
    { item: "هواکش", stock: "15 عدد", status: "کم موجود" },
    { item: "توری پنجره", stock: "60 عدد", status: "موجود" },
    { item: "آسفالت", stock: "500 تن", status: "سفارش داده شده" },
    { item: "چسب", stock: "250 کیلوگرم", status: "موجود" },
    { item: "فیلتر هوا", stock: "80 عدد", status: "کم موجود" },
    { item: "پلاک ساختمان", stock: "40 عدد", status: "موجود" },
    { item: "بتن آماده", stock: "120 متر مکعب", status: "سفارش داده شده" },
  ];